version: "3"

services:
  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-27-feb-2024/motion-backend-assigment/team-4/motion:latest
    ports:
      - "8000:8000"
    #command: 'tail -f /dev/null'
    command: 'sh /scripts/dev.sh'
    volumes:
      - ./backend:/backend
    env_file:
      - ./envs/dev.env
    depends_on:
      - database

  database:
    image: postgres:16
    ports:
      - "5555:5432"
    env_file:
      - ./envs/dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


