# Generated by Django 5.0.3 on 2024-04-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
